### PR TITLE
Adding random generations

### PR DESCRIPTION
**Pull request by andrechalom**
For #16 and #15

### CODE REVIEW

**Comment by piklprado** [comment]
The last rank does not show up in random draws from rads:
```r
> any(rzipf(1e6, N=100, s=1)==100)
[1] FALSE
> any(rmand(1e6, N=100, s=1, v=2)==100)
[1] FALSE
> any(rgs(1e6, S=100, k=0.1)==100)
[1] FALSE
```

**Comment by andrechalom** [comment]
The problem here is that `qzipf` (inside `rzipf`) is returning the largest `q` that is smaller than the random generated number, while we need the opposite. I'm rewriting the random functions of discrete distributions in a similar manner as this:

```R
N <- 50
s <- 0.8 
rzipf2<-function(n, N, s) {
  rr <- runif(n)
  d1 <- dzipf(1, N,s)
  qz <- qzipf(rr, N, s)
  qz[ rr < d1 ] <- 0
  1+qz
}
RF <- rzipf2(1e6, N, s)
DF <- dzipf(1:N, N, s)  
DRF <- hist(RF, plot=F, breaks=0:N)$density
barplot(DF, col="gray80", main="rzipf")
barplot(DRF, add=T, col="#FFFF0099")
legend("topright", legend=c("predicted", "generated"), fill=c("gray80", "#ffff00"))
```
rzipf

**Comment by andrechalom** [comment]
(PS: I still need to evaluate which distributions require this fix; mand and gs for sure, but maybe all discrete or all 1-based discrete distributions?)

**Comment by piklprado** [comment]
Maybe this help: http://www.jstatsoft.org/article/view/v011i03

**Comment by piklprado** [comment]
My first guess is that this is necessary only for rad distributions.

**Comment by andrechalom** [comment]
OK, the [r] functions available are:
- rbs; rpareto (continuous, ok)
- rls; rpoig; rpoilog; rpoix; rpower (tested, already working as expected)
- rgs; rmand; rmzsm; rpowbend; rrbs; rvolkov; rzipf (fixed)

Also, in the last commit, I have reduced the namespace import from `poilog` to avoid clashes between their rpoilog and ours.

**Comment by andrechalom** [comment]
Working on conflicts from merging confint...

**Comment by piklprado** [comment]
I ran more tests and seems ok to me, can merge once you worked out the conflicts.

**Pull request merged**
