### PR TITLE
Merging confint to dev

### PR DESCRIPTION
**Pull request by andrechalom**

### CODE REVIEW

**Comment by piklprado** [comment]
Any easy way to have a show method similar to that of `confint`?

**Comment by andrechalom** [comment]
Actually, the easy way is by creating a 'likelregions' class. Will work on
that ;)

**Comment by piklprado** [comment]
I increased the default value for `nseg` in `likelregions` to assure that the interval can be found when the calculated profile limits are close to the likelihood ratio:
```r
## From a zero-truncated negative binomial
> x1 <- c(1,1,1,1,1,1,1,1,2,3,3,5,8,9,9,11,14,20,22,22,22,26,
+         26,31,35,35,39,44,61,62,106,110,121,149,167,209,225,
+         227,271,294,301,356,398,477,572,725,737,1121)
> x1.nb <- fitnbinom(x1, start=c(size=0.1, mu=100))
> x1.nb.p <- profile(x1.nb)
par(mfrow=c(1,2))
There were 50 or more warnings (use warnings() to see the first 50)
> 
```
likelregions

```r
> likelregions(x1.nb.p, nseg=20)
$size
$size[[1]]
[1] 0.05307468 0.33894039


$mu
$mu[[1]]
[1]       NA 194.6147


> confint(x1.nb.p)
          2.5 %      97.5 %
size 0.05341809   0.3303096
mu   1.84219980 189.3379853
Warning messages:
1: In .local(object, parm, level, ...) :
  non-monotonic spline fit to profile (size): reverting from spline to linear approximation
2: In .local(object, parm, level, ...) :
  non-monotonic spline fit to profile (mu): reverting from spline to linear approximation
> likelregions(x1.nb.p, nseg=100)
$size
$size[[1]]
[1] 0.05251673 0.33864652


$mu
$mu[[1]]
[1]   1.215512 194.774318

```

**Comment by andrechalom** [comment]
Now with a minimal "show" method: 

```R
> likelregions(x1.nb.p)
Likelihood regions for ratio = 2.079442 
size:
[1] 0.05251673 0.33864652
mu:
[1]   1.215512 194.774318
```

**Comment by piklprado** [comment]
Kind of OCD, but the numbers not aligning were annoying me:

```r
> profile(fitvolkov(okland)) -> trouble
Warning message:
In mle2(minuslogl = function (theta, m, J)  :
  convergence failure: code=52 (ERROR: ABNORMAL_TERMINATION_IN_LNSRCH)
> trouble@profile[1][[1]][11,1]<-0.35
> likelregions(trouble, ratio=0.13)
Likelihood regions for ratio = 0.13 
theta:
[1] 3.615336 7.514082
[1]  9.180481 12.052138
m:
[1] 0.01489487 0.15242468
```
I solved this using `print(matrix(unlist))` (#be44d2b). Maybe a long way, but it is working:

```r
> likelregions(trouble, ratio=0.13)
Likelihood regions for ratio = 0.13 

 theta:
        lower     upper
[1,] 3.615336  7.514082
[2,] 9.180481 12.052138

 m:
          lower     upper
[1,] 0.01489487 0.1524247
```
Waiting for @andrechalom  checks now.

**Pull request merged**
