### PR TITLE
Fixing support for zipf, zipf-mandelbrodt and broken-stick

### PR DESCRIPTION
**Pull request by piklprado**
Support of Zipf, Zipf-mandelbrodt and Broken-stick do not include zero abundances or zero-th rank. PDF and CDF functions fixed accordingly.

### CODE REVIEW

**Comment by andrechalom** [comment]
I'm still having some problems with broken stick distribution:

```R
# pbs() does not agree with sum(dbs())
> sum(dbs(0:100, 1000, 20))
[1] 0.8568645
> pbs(100, 1000, 20)
[1] 0.8649148
# sum(dbs()) does not converge to 1
> sum(dbs(0:1000, 1000, 20))
[1] 0.9905285
> sum(dbs(0:2000, 1000, 20))
[1] 0.9905285
```

These are the same values I get from sads v0.1.10, with the sums starting in 1.

On branch master, we have the opposite error, as dbs(0, ...) is not zero:
```R
>  sum(dbs(0:1000, 1000, 20))
[1] 1.009528
> sum(dbs(0:100, 1000, 20))
[1] 0.8758645
```

No errors found on zipf, mand or gs.

**Comment by andrechalom** [comment]
It seems that the problem is not on the implementation, but on the formula
 `dbs = (1 - x/N)^(S-2) (S - 1)/N`

Wolfram Alpha agrees with the result of `sum(dbs(1:1000, 1000,20)) = 0.9905285`: http://www.wolframalpha.com/input/?i=sum+of+%281+-+x%2FN%29^%28S-2%29+%28S+-+1%29%2FN+from+x+%3D+1+to+x%3DN+with+S%3D25+and+N%3D1000

It is also worth mentioning that the alternative expression of `p(x) ~ S/N exp(-S x/N)` given by May 1975 p. 114 also fails to integrate to 1: http://www.wolframalpha.com/input/?i=sum+of+%28S%2FN+e^%28-S+x+%2FN%29%29+from+x+%3D+1+to+x%3DN+with+S%3D20+and+N%3D1000

**Comment by andrechalom** [comment]
As `pbs(x, N, s)` seem to give the rigth answer, I've calculated

```
dbs(x) = pbs(x) - pbs(x-1)
dbs(x) = 1 + N (1-x/N)^S/(x-N) - 1 - N (1-(x-1)/N)^S/(x-1-N))
dbs(x) = N [ (1-x/N)^S/(x-N) - (1-(x-1)/N)^S/(x-1-N)) ]
dbs(x) = N^(1-S) [ (N-x+1)^(S-1) - (N-x)^(S-1) ]
```

The expression above provides a `dbs` function that solves the summation problems above (sum(dbs()) == 1), and it is very interesting to see that the expression by May 1975 shows up in the series expansion of this formula around x=0: http://www.wolframalpha.com/input/?i=N+*+%28+%28%28%281-x%2FN%29^S%29%2F%28x-N%29%29+-+%28%281-%28x-1%29%2FN%29^S%2F%28x-1-N%29%29+%29

I don't know where does the formula for pbs found in the package comes from, though. It is certainly not from dbs and algebra, as they clearly diverge, but I could not find it on the references.

The problem with the simplified expression is that it is very unsuited for numerical evaluations, as the (1-S) exponents get very close to zero for a reasonable S.

**Comment by piklprado** [comment]
Oops, working on this too.
The original formula comes from expression D.5 in May (1975). Maybe I am missing something here, but I think the summation does not match because dbs is a continuous PDF:

```r
> integrate(dbs, 0, 100, N=1000, S=20)
0.8649148 with absolute error < 9.6e-15
> pbs(100, 1000, 20)
[1] 0.8649148
> integrate(dbs, 0, N-500, N=1000, S=20)
1 with absolute error < 1.1e-14
> pbs(500, 1000, 20)
[1] 0.9999981
```
Note that numerical integration provides an independent check here because `pbs` uses the antiderivative of expression D.5 of May (1975).

**Comment by piklprado** [comment]
Also added some small tweaks in `qbs` and `qgs` (argument `ties='ordered'` seems to help).

**Comment by andrechalom** [comment]
D'oh! I got so used to continuous distributions that I completely forgot that some distributions are continuous. We can revert my changes.

I haven't found the tweaks in `qbs` and `qgs`, have you pushed them?

**Comment by andrechalom** [comment]
D'oh, found them. I was expecting them to be in another order.

**Comment by piklprado** [comment]
No probs, I also forgot that and changed the support for dbs in this
branch. But the fixes in dzipf and dmand seems necessary anyway.

2015-12-10 23:42 GMT-02:00 andrechalom <notifications@github.com>:

> D'oh! I got so used to continuous distributions that I completely forgot
> that some distributions are continuous. We can revert my changes.
>
> I haven't found the tweaks in qbs and qgs, have you pushed them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/piLaboratory/sads/pull/115#issuecomment-163807254>.
>



-- 

*Paulo Inácio de Knegt López de Prado
*Depto. de Ecologia - Instituto de Biociências -
USPhttp://ecologia.ib.usp.br/let <http://ecologia.ib.usp.br/get>
Rua do Matão, travessa 14, nº 321
Cid. Universitária, São Paulo - SP - Brasil
CEP 05508-900
+55-11-30910963 (sala)
+55-11-30917600 (Secretaria)

**Pull request merged**
