### PR TITLE
Fixes redundancy in the distr slot

### PR DESCRIPTION
**Pull request by andrechalom**
For #85

### CODE REVIEW

**Comment by piklprado** [comment]
While checking this PR I found many signature errors. They seem not related to this PR see #88, but I fixed one of the problems in a commit to this PR (0a1ab4ec89533c400d0380adcb657aea9aff7e44). But I think most of the remaining problems are not related to the fixes in conditional I made in this case.

**Comment by piklprado** [comment]
Some errors seem to be related to this PR, as they do not occur in the release and dev branch:
```r
> radpred(moths, rad="gs", coef=as.list(coef(moths.gs))) 
Error in data.frame(rank = 1:S, abund = ab) (from sads-methods.R#297) : objeto 'ab' não encontrado
> radpred(moths, rad="gs", coef=as.list(coef(moths.gs))) 
Error in data.frame(rank = 1:S, abund = ab) (from sads-methods.R#297) : objeto 'ab' não encontrado
> radpred(moths, sad="ls", coef=as.list(coef(moths.ls)), distr="D")
Error in xy.coords(x, y) (from sads-methods.R#323) : objeto 'X' não encontrado
Além disso: Warning message:
In .local(object, sad, rad, coef, trunc, distr) :
  The parameter distr has been deprecated and is ignored, see ?distr
> radpred(moths, sad="lnorm", coef=as.list(coef(moths.ln)), distr="C")
Error in data.frame(rank = 1:S, abund = ab) (from sads-methods.R#347) : objeto 'ab' não encontrado
Além disso: Warning message:
In .local(object, sad, rad, coef, trunc, distr) :
  The parameter distr has been deprecated and is ignored, see ?distr
```

**Comment by andrechalom** [comment]
It seems to me that most of these errors were actually **caused** by the fixes in commit 0a1ab4e, so I have reverted them in 79aacee. Maybe you could explain what is the logical error that you addressed in that commit?

What's left are the problems in `octavpred`:

```R 
> octavpred(moths, rad="gs", coef=as.list(coef(moths.gs)))
```
Raises an error for "hist.default, some x not counted". I will look on that later.

```R
> octavpred(sad="ls", coef=as.list(coef(moths.ls)), S=length(moths), N=sum(moths))
```
This raises an error about "oct" being missing, which I think is accurate. `octavpred` methods based on a fitted object generate the "oct"s using the maximum abundance, which is something that we cannot determine from S and N individually. We *can* make a rough guess that max(x) >= N and use N instead... but that will not generate any negative octave, so we should keep our eyes open for that.

However, if we provided oct in the current code, this raised "missing trunc". Fixed both issues on 58c7b5a.

On a side note, we should keep these logs to include in the test suite later.

**Comment by piklprado** [comment]
I will check the whole thing later, but here goes a quick answer to the 1st question. The logical error I was trying to solve was caused by the missing trunc argument, please try this in dev branch

```r
radpred(sad="ls", coef=as.list(coef(moths.ls)), S=length(moths), N=sum(moths), distr="D")
```

**Comment by andrechalom** [comment]
Confirmed that it does not work on master or dev, but working on distr branch now.

**Comment by andrechalom** [comment]
Re-reading the code, I have at last found out that I was counting on `! missing(...) & ! nan(...)` to work, but the right way to do it was using `! missing(...) && ! nan(...)`, see section 8.2.17 from the [R Inferno] (http://www.burns-stat.com/pages/Tutor/R_inferno.pdf)

**Comment by andrechalom** [comment]
See #89 before merging this

**Pull request merged**
