### PR TITLE
Introducing the powerbend distribution

### PR DESCRIPTION
**Pull request by andrechalom**
Introducing the Pueyo's powerbend family.

### CODE REVIEW

**Comment by piklprado** [comment]
Que boa notícia! Hj e amanhã tá lotado, mas no máximo no fds eu verifico
este PR, estou muito curioso pra ver com este fitting se comporta.

Vc viu meus comentários sobre o argumento perston no issue #67? Mantemos o
PR #73 aberto até resolver isso ou já dou merge no que foi feito?

Abrs

PI

2015-09-23 13:12 GMT-03:00 andrechalom <notifications@github.com>:

> Introducing the Pueyo's powerbend family.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/piLaboratory/sads/pull/83
> Commit Summary
>
>    - Implementing Puyeo's Power Bend
>    - Initial version for fitting powbend family
>    - Typo in NAMESPACE
>    - Merge branch 'dev' into Fix7
>    - Documentation, NEWS, splitting files for powbend
>    - Merging Powbend
>    - Merge branch 'andrechalom-Fix7' into Powerbend
>
> File Changes
>
>    - *M* NAMESPACE
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-0> (12)
>    - *M* NEWS <https://github.com/piLaboratory/sads/pull/83/files#diff-1>
>    (3)
>    - *A* R/dpowbend.R
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-2> (11)
>    - *A* R/fitpowbend.R
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-3> (26)
>    - *A* R/ppowbend.R
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-4> (6)
>    - *A* R/qpowbend.R
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-5> (8)
>    - *M* R/utils.R
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-6> (17)
>    - *A* man/dpowbend.Rd
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-7> (104)
>    - *M* man/fitsad.Rd
>    <https://github.com/piLaboratory/sads/pull/83/files#diff-8> (36)
>
> Patch Links:
>
>    - https://github.com/piLaboratory/sads/pull/83.patch
>    - https://github.com/piLaboratory/sads/pull/83.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/piLaboratory/sads/pull/83>.
>



-- 

*Paulo Inácio de Knegt López de Prado
*Depto. de Ecologia - Instituto de Biociências -
USPhttp://ecologia.ib.usp.br/let <http://ecologia.ib.usp.br/get>
Rua do Matão, travessa 14, nº 321
Cid. Universitária, São Paulo - SP - Brasil
CEP 05508-900
+55-11-30910963 (sala)
+55-11-30917600 (Secretaria)

**Comment by andrechalom** [comment]
It seems that the fits from `powbend` are always better than the simple `power` function. They are also good competitors with `pareto`. The function is still a bit quirky on some corner cases, so it might not always be numerically stable.
```R
> dataset <- moths
> AICtab(fitpowbend(dataset), fitpower(dataset), fitpareto(dataset))
                    dAIC df
fitpareto(dataset)   0.0 1
fitpowbend(dataset)  4.8 2
fitpower(dataset)   92.6 1

> dataset <- birds
> AICtab(fitpowbend(dataset), fitpower(dataset), fitpareto(dataset))
                    dAIC df
fitpowbend(dataset)  0.0 2
fitpareto(dataset)  32.2 1
fitpower(dataset)   54.1 1

> dataset <- bci
> AICtab(fitpowbend(dataset), fitpower(dataset), fitpareto(dataset))
                    dAIC  df
fitpowbend(dataset)   0.0 2
fitpareto(dataset)   56.1 1
fitpower(dataset)   129.1 1

> dataset <- okland
> AICtab(fitpowbend(dataset), fitpower(dataset), fitpareto(dataset))
                    dAIC df
fitpareto(dataset)   0.0 1 
fitpowbend(dataset) 19.9 2 
fitpower(dataset)   33.7 1 
```

**Comment by piklprado** [comment]
Could reproduce the values but got convergence failure:

```r
> AICtab(fitpowbend(dataset), fitpower(dataset), fitpareto(dataset))
                    dAIC df
fitpareto(dataset)   0.0 1 
fitpowbend(dataset)  4.8 2 
fitpower(dataset)   92.6 1 
Warning messages:
1: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
2: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
3: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
4: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
5: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
6: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
7: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
8: In dpowbend(x, s, omega, log = TRUE) : NaNs produced
9: In mle2(function (s, omega)  : couldn't invert Hessian
10: In mle2(function (s, omega)  :
  convergence failure: code=52 (ERROR: ABNORMAL_TERMINATION_IN_LNSRCH)
```

**Comment by andrechalom** [comment]
Yes, that's correct. I did not check for convergence. More than anything, I think this is a sign that the power distribution is really bad at fitting sads, if even a ABNORMAL_TERMINATION in powbend fits all those datasets better...

**Comment by andrechalom** [comment]
Back to work here

**Comment by andrechalom** [comment]
I've double checked the results from the polylog function `LiE`, and they agree with Wolfram Alpha's for 5 significance digits for all values tested. I've also checked to see if `dpowbend(x, s, omega)` converged to `dpower(x, s)` as omega -> 0, and it does, altought at a very slow rate. This is specially true for x=1 and s ~ 1, which is probably the reason why `fitpowbend` seems to converge to s ~ 1.

**Comment by andrechalom** [comment]
See comments in #7 ref. the problems above. I believe we are now ready for merging this distribution.

**Comment by andrechalom** [comment]
Fixed the other PRs to work with the powbend as well

On Fri, Dec 4, 2015 at 9:11 PM, Paulo Inácio Prado <notifications@github.com

**Pull request merged**
